version: '3.8'

# Minimal setup for M1/M2 Macs - just databases
services:
  postgres:
    image: pgvector/pgvector:pg16
    platform: linux/amd64
    container_name: legal-postgres
    environment:
      POSTGRES_USER: legal_user
      POSTGRES_PASSWORD: legal_pass
      POSTGRES_DB: legal_research
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U legal_user -d legal_research"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    platform: linux/amd64
    container_name: legal-redis
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  postgres_data:
  redis_data: