# Nixpacks configuration for Railway deployment
[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "postgresql"]

[phases.install]
cmds = [
    "pip install -r backend/requirements.txt --user"
]

[start]
cmd = "cd backend && python -m uvicorn simple_api:app --host 0.0.0.0 --port ${PORT:-8000}"