# Nixpacks configuration for Railway deployment
[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "postgresql", "poppler_utils", "ghostscript"]

[phases.install]
cmds = [
    "python -m venv /opt/venv",
    ". /opt/venv/bin/activate && pip install -r backend/requirements.txt"
]

[start]
cmd = ". /opt/venv/bin/activate && cd backend && uvicorn main:app --host 0.0.0.0 --port ${PORT:-8000}"