#!/usr/bin/env python3
"""
Bulk import cases that are cited by existing database cases but missing from the database.

Reads data/cited_but_missing.json (generated by find_cited_but_missing.py),
fetches opinion text from CourtListener API, and inserts into production PostgreSQL.

Usage:
    python scripts/import_cited_missing.py                    # Import all (min 5 citations)
    python scripts/import_cited_missing.py --limit 50         # Import first 50
    python scripts/import_cited_missing.py --min-citations 3  # Lower citation threshold
    python scripts/import_cited_missing.py --dry-run          # Preview without importing
"""

import asyncio
import argparse
import json
import os
from datetime import datetime
from pathlib import Path

import asyncpg
import httpx
from bs4 import BeautifulSoup
from dotenv import load_dotenv

load_dotenv()

DATABASE_URL = os.getenv("PROD_DATABASE_URL") or os.getenv("DATABASE_URL")
COURTLISTENER_TOKEN = os.getenv("COURTLISTENER_API_KEY") or os.getenv("COURTLISTENER_TOKEN")
DATA_FILE = Path(__file__).parent.parent / "data" / "cited_but_missing.json"


async def fetch_case_from_api(client: httpx.AsyncClient, cluster_id: str) -> dict | None:
    """Fetch case metadata from CourtListener API."""
    headers = {}
    if COURTLISTENER_TOKEN:
        headers["Authorization"] = f"Token {COURTLISTENER_TOKEN}"

    try:
        response = await client.get(
            f"https://www.courtlistener.com/api/rest/v4/clusters/{cluster_id}/",
            headers=headers,
            timeout=30.0
        )

        if response.status_code == 429:
            print("  Rate limited, waiting 60s...")
            await asyncio.sleep(60)
            response = await client.get(
                f"https://www.courtlistener.com/api/rest/v4/clusters/{cluster_id}/",
                headers=headers,
                timeout=30.0
            )

        if response.status_code != 200:
            print(f"  API error: {response.status_code}")
            return None

        cluster = response.json()

        # Get reporter citations
        citations = []
        if cluster.get("citations"):
            for cite_url in cluster["citations"][:5]:
                cite_id = cite_url.rstrip('/').split('/')[-1]
                cite_resp = await client.get(
                    f"https://www.courtlistener.com/api/rest/v4/citations/{cite_id}/",
                    headers=headers,
                    timeout=15.0
                )
                if cite_resp.status_code == 200:
                    cite_data = cite_resp.json()
                    citations.append(f"{cite_data.get('volume', '')} {cite_data.get('reporter', '')} {cite_data.get('page', '')}")

        return {
            "id": str(cluster_id),
            "title": cluster.get("case_name") or cluster.get("case_name_full", "Unknown"),
            "decision_date": cluster.get("date_filed"),
            "court_id": cluster.get("court_id"),
            "reporter_cite": citations[0] if citations else None,
            "source_url": cluster.get("absolute_url"),
        }

    except Exception as e:
        print(f"  Error fetching metadata: {e}")
        return None


async def fetch_opinion_text(client: httpx.AsyncClient, cluster_id: str) -> str:
    """Fetch opinion text via CourtListener API (sub_opinions endpoint)."""
    headers = {}
    if COURTLISTENER_TOKEN:
        headers["Authorization"] = f"Token {COURTLISTENER_TOKEN}"

    try:
        # Fetch opinion directly by ID (opinion ID often matches cluster ID)
        response = await client.get(
            f"https://www.courtlistener.com/api/rest/v4/opinions/{cluster_id}/",
            headers=headers,
            timeout=30.0
        )

        if response.status_code == 429:
            print("  Rate limited, waiting 60s...")
            await asyncio.sleep(60)
            response = await client.get(
                f"https://www.courtlistener.com/api/rest/v4/opinions/{cluster_id}/",
                headers=headers,
                timeout=30.0
            )

        if response.status_code != 200:
            return ""

        opinion = response.json()

        # Try plain text first, then extract from HTML variants
        if opinion.get("plain_text"):
            return opinion["plain_text"]

        # Try HTML fields in order of preference
        for field in ["html_lawbox", "html", "html_columbia", "html_with_citations", "xml_harvard"]:
            html_content = opinion.get(field, "")
            if html_content:
                soup = BeautifulSoup(html_content, 'html.parser')
                text = soup.get_text(separator='\n', strip=True)
                if len(text) > 100:
                    return text

    except Exception as e:
        print(f"  Error fetching opinion text: {e}")

    return ""


async def import_cited_missing(limit: int = None, min_citations: int = 5,
                               dry_run: bool = False, fetch_text: bool = False):
    """Import missing cited cases from CourtListener."""

    if not DATABASE_URL:
        print("ERROR: Set PROD_DATABASE_URL or DATABASE_URL")
        return

    # Load input data
    if not DATA_FILE.exists():
        print(f"ERROR: {DATA_FILE} not found. Run find_cited_but_missing.py first.")
        return

    with open(DATA_FILE) as f:
        all_cases = json.load(f)

    # Filter to cases with cluster_id and meeting citation threshold
    cases = [c for c in all_cases if c.get("cluster_id") and c["times_cited"] >= min_citations]
    # Deduplicate by cluster_id (some cases appear twice with different citations)
    seen = set()
    unique_cases = []
    for c in cases:
        if c["cluster_id"] not in seen:
            seen.add(c["cluster_id"])
            unique_cases.append(c)
    cases = unique_cases
    cases.sort(key=lambda c: c["times_cited"], reverse=True)

    if limit:
        cases = cases[:limit]

    print(f"Total in file: {len(all_cases)}")
    print(f"Unique with cluster_id & >= {min_citations} citations: {len(cases)}")
    if limit:
        print(f"Limited to: {limit}")
    print()

    if dry_run:
        print("DRY RUN - would import these cases:")
        for c in cases:
            print(f"  [{c['times_cited']} cites] {c['case_name']} — {c['citation']} (cluster {c['cluster_id']})")
        return

    # Connect to database
    print("Connecting to database...")
    conn = await asyncpg.connect(DATABASE_URL)

    try:
        if fetch_text:
            await fetch_text_for_stubs(conn, cases, limit)
        else:
            await import_new_cases(conn, cases)

    finally:
        await conn.close()


async def fetch_text_for_stubs(conn, cases, limit):
    """Fetch opinion text for existing stub cases (no content)."""
    # Find stubs: cases in DB with no content
    cluster_ids = [c["cluster_id"] for c in cases]
    stubs = await conn.fetch("""
        SELECT id, title, source_url FROM cases
        WHERE id = ANY($1)
          AND (content IS NULL OR length(content) < 100)
        ORDER BY id
    """, cluster_ids)

    if limit:
        stubs = stubs[:limit]

    print(f"Found {len(stubs)} stubs needing opinion text")
    if not stubs:
        print("All cases already have opinion text!")
        return

    updated = 0
    failed = 0

    async with httpx.AsyncClient() as client:
        for i, stub in enumerate(stubs, 1):
            print(f"[{i}/{len(stubs)}] {stub['title'][:60]}")

            print(f"  Fetching opinion text via API...")
            content = await fetch_opinion_text(client, stub["id"])

            if content and len(content) > 100:
                try:
                    await conn.execute("""
                        UPDATE cases SET content = $1, updated_at = NOW()
                        WHERE id = $2
                    """, content, stub["id"])
                    updated += 1
                    print(f"  Updated with {len(content):,} chars")
                except Exception as e:
                    print(f"  ERROR updating: {e}")
                    failed += 1
            else:
                print(f"  No opinion text found on page")
                failed += 1

            await asyncio.sleep(1)

    print(f"\n{'='*50}")
    print(f"FETCH TEXT COMPLETE")
    print(f"{'='*50}")
    print(f"Updated: {updated}")
    print(f"Failed/no text: {failed}")
    print(f"{'='*50}")


async def import_new_cases(conn, cases):
    """Import cases not yet in the database."""
    # Check which cases already exist
    existing_ids = set()
    for c in cases:
        row = await conn.fetchrow("SELECT id FROM cases WHERE id = $1", c["cluster_id"])
        if row:
            existing_ids.add(c["cluster_id"])

    to_import = [c for c in cases if c["cluster_id"] not in existing_ids]
    print(f"Already in DB: {len(existing_ids)}")
    print(f"To import: {len(to_import)}")
    print()

    if not to_import:
        print("Nothing to import!")
        return

    imported = 0
    failed = 0

    async with httpx.AsyncClient() as client:
        for i, case in enumerate(to_import, 1):
            print(f"[{i}/{len(to_import)}] {case['case_name']} ({case['times_cited']} cites)")

            cluster_id = case["cluster_id"]

            # Fetch case metadata from API
            print(f"  Fetching metadata for cluster {cluster_id}...")
            case_data = await fetch_case_from_api(client, cluster_id)
            await asyncio.sleep(0.5)

            if not case_data:
                print(f"  FAILED: Could not fetch metadata")
                failed += 1
                await asyncio.sleep(1)
                continue

            # Use case_name from our JSON if API returned "Unknown"
            if case_data["title"] == "Unknown" and case.get("case_name"):
                case_data["title"] = case["case_name"]

            # Use reporter_cite from our JSON if API didn't return one
            if not case_data["reporter_cite"] and case.get("citation"):
                case_data["reporter_cite"] = case["citation"]

            # Fetch opinion text
            print(f"  Fetching opinion text...")
            content = await fetch_opinion_text(client, cluster_id)
            if content:
                print(f"  Got {len(content):,} chars of opinion text")
            else:
                print(f"  No opinion text available (stub entry)")

            # Parse decision date
            decision_date = None
            date_str = case_data.get("decision_date") or case.get("date_filed")
            if date_str:
                try:
                    decision_date = datetime.strptime(date_str, '%Y-%m-%d').date()
                except (ValueError, TypeError):
                    pass

            # Insert into cases table
            try:
                await conn.execute("""
                    INSERT INTO cases (id, title, decision_date, court_id, reporter_cite, content, source_url, created_at)
                    VALUES ($1, $2, $3, $4, $5, $6, $7, NOW())
                    ON CONFLICT (id) DO UPDATE SET
                        title = EXCLUDED.title,
                        content = COALESCE(EXCLUDED.content, cases.content),
                        updated_at = NOW()
                """,
                    case_data["id"],
                    case_data["title"],
                    decision_date,
                    case_data.get("court_id"),
                    case_data.get("reporter_cite"),
                    content or None,
                    case_data.get("source_url")
                )

                imported += 1
                print(f"  Imported!")

            except Exception as e:
                print(f"  ERROR inserting: {e}")
                failed += 1

            # Rate limit: 1 second between API calls
            await asyncio.sleep(1)

    print(f"\n{'='*50}")
    print(f"IMPORT COMPLETE")
    print(f"{'='*50}")
    print(f"Imported: {imported}")
    print(f"Skipped (already in DB): {len(existing_ids)}")
    print(f"Failed:   {failed}")
    print(f"{'='*50}")
    print(f"\nNext step: rebuild citations with:")
    print(f"  PROD_DATABASE_URL=\"...\" python3 scripts/import_citations_local.py")


async def main():
    parser = argparse.ArgumentParser(description="Import missing cited cases from CourtListener")
    parser.add_argument("--limit", type=int, help="Max number of cases to import")
    parser.add_argument("--min-citations", type=int, default=5,
                        help="Only import cases cited at least N times (default: 5)")
    parser.add_argument("--dry-run", action="store_true",
                        help="Preview cases without importing")
    parser.add_argument("--fetch-text", action="store_true",
                        help="Fetch opinion text for existing stubs (no content)")

    args = parser.parse_args()

    await import_cited_missing(
        limit=args.limit,
        min_citations=args.min_citations,
        dry_run=args.dry_run,
        fetch_text=args.fetch_text
    )


if __name__ == "__main__":
    asyncio.run(main())
